export enum PermissionNameType {
  GET_USER = 'GET_USER',
  GET_USERS = 'GET_USERS',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  // DELETE_USER = 'DELETE_USER',

  GET_ROLE = 'GET_ROLE',
  GET_ROLES = 'GET_ROLES',
  CREATE_ROLE = 'CREATE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  // DELETE_ROLE = 'DELETE_ROLE',

  GET_CUSTOMER = 'GET_CUSTOMER',
  GET_CUSTOMERS = 'GET_CUSTOMERS',
  CREATE_CUSTOMER = 'CREATE_CUSTOMER',
  UPDATE_CUSTOMER = 'UPDATE_CUSTOMER',

  GET_PRODUCT = 'GET_PRODUCT',
  GET_PRODUCTS = 'GET_PRODUCTS',
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',

  GET_SERVICE = 'GET_SERVICE',
  GET_SERVICES = 'GET_SERVICES',
  CREATE_SERVICE = 'CREATE_SERVICE',
  UPDATE_SERVICE = 'UPDATE_SERVICE',
}
